/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.budgeter;

import java.awt.CardLayout;
import javax.swing.JLabel;

/**
 *
 * @author LENOVO
 */
public class jframe extends javax.swing.JFrame {

    /**
     * Creates new form jframe
     */
    CardLayout cardLayout;
    CardLayout cardLayout2;
    
    public jframe() {
        initComponents();
        cardLayout = (CardLayout)(panelDisplay.getLayout());
        cardLayout2 = (CardLayout)(transactionSplit.getLayout());
        cardLayout.show(panelDisplay, "cardHome");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        panelMenu = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnTransaction = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        panelDisplay = new javax.swing.JPanel();
        transactionSplit = new javax.swing.JPanel();
        panelTransaction = new javax.swing.JPanel();
        btnToIncome = new javax.swing.JButton();
        btnToExpense = new javax.swing.JButton();
        incomePanel = new javax.swing.JPanel();
        lblAddIncome = new javax.swing.JLabel();
        fieldValueIncome = new javax.swing.JTextField();
        fieldTimeIncome = new javax.swing.JTextField();
        fieldValueIncome1 = new javax.swing.JTextField();
        btnBackIncome = new javax.swing.JButton();
        expensePanel = new javax.swing.JPanel();
        lblAddExpense = new javax.swing.JLabel();
        fieldValueExpense = new javax.swing.JTextField();
        fieldTimeExpense = new javax.swing.JTextField();
        fieldExpenseType = new javax.swing.JTextField();
        btnBackExpense = new javax.swing.JButton();
        homePanel = new javax.swing.JPanel();
        historyPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setBackground(new java.awt.Color(242, 242, 255));

        btnHome.setBackground(new java.awt.Color(242, 242, 255));
        btnHome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnHome.setText("Home");
        btnHome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHome.setMaximumSize(new java.awt.Dimension(120, 55));
        btnHome.setMinimumSize(new java.awt.Dimension(120, 55));
        btnHome.setPreferredSize(new java.awt.Dimension(150, 55));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnTransaction.setBackground(new java.awt.Color(242, 242, 255));
        btnTransaction.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnTransaction.setText("Transaction");
        btnTransaction.setActionCommand("Expense");
        btnTransaction.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTransaction.setMaximumSize(new java.awt.Dimension(120, 55));
        btnTransaction.setMinimumSize(new java.awt.Dimension(120, 55));
        btnTransaction.setPreferredSize(new java.awt.Dimension(150, 55));
        btnTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransactionActionPerformed(evt);
            }
        });

        btnHistory.setBackground(new java.awt.Color(242, 242, 255));
        btnHistory.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnHistory.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHistory.setLabel("History");
        btnHistory.setMaximumSize(new java.awt.Dimension(120, 55));
        btnHistory.setMinimumSize(new java.awt.Dimension(120, 55));
        btnHistory.setPreferredSize(new java.awt.Dimension(150, 55));
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panelMenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHistory, btnHome, btnTransaction});

        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(313, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(panelMenu);

        panelDisplay.setBackground(new java.awt.Color(255, 255, 239));
        panelDisplay.setLayout(new java.awt.CardLayout());

        transactionSplit.setLayout(new java.awt.CardLayout());

        panelTransaction.setBackground(new java.awt.Color(0, 204, 204));

        btnToIncome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnToIncome.setText("Income");
        btnToIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToIncomeActionPerformed(evt);
            }
        });

        btnToExpense.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnToExpense.setText("Expense");
        btnToExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToExpenseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTransactionLayout = new javax.swing.GroupLayout(panelTransaction);
        panelTransaction.setLayout(panelTransactionLayout);
        panelTransactionLayout.setHorizontalGroup(
            panelTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransactionLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btnToIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                .addComponent(btnToExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        panelTransactionLayout.setVerticalGroup(
            panelTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransactionLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnToIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnToExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(538, Short.MAX_VALUE))
        );

        transactionSplit.add(panelTransaction, "cardTransBase");
        panelTransaction.getAccessibleContext().setAccessibleParent(panelDisplay);

        incomePanel.setBackground(new java.awt.Color(255, 231, 231));

        lblAddIncome.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        lblAddIncome.setText("Add Income");

        fieldValueIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldValueIncomeActionPerformed(evt);
            }
        });

        fieldTimeIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTimeIncomeActionPerformed(evt);
            }
        });

        fieldValueIncome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldValueIncome1ActionPerformed(evt);
            }
        });

        btnBackIncome.setText("Back");
        btnBackIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackIncomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout incomePanelLayout = new javax.swing.GroupLayout(incomePanel);
        incomePanel.setLayout(incomePanelLayout);
        incomePanelLayout.setHorizontalGroup(
            incomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incomePanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(incomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldValueIncome, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                    .addComponent(lblAddIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldTimeIncome, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                    .addComponent(fieldValueIncome1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, incomePanelLayout.createSequentialGroup()
                .addContainerGap(651, Short.MAX_VALUE)
                .addComponent(btnBackIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        incomePanelLayout.setVerticalGroup(
            incomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incomePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblAddIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(fieldTimeIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(fieldValueIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(fieldValueIncome1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(btnBackIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        fieldValueIncome.getAccessibleContext().setAccessibleName("");
        fieldTimeIncome.getAccessibleContext().setAccessibleName("");
        fieldValueIncome1.getAccessibleContext().setAccessibleName("");

        transactionSplit.add(incomePanel, "cardIncome");

        expensePanel.setBackground(new java.awt.Color(212, 249, 249));

        lblAddExpense.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        lblAddExpense.setText("Add Expense");

        fieldValueExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldValueExpenseActionPerformed(evt);
            }
        });

        fieldExpenseType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldExpenseTypeActionPerformed(evt);
            }
        });

        btnBackExpense.setText("Back");
        btnBackExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackExpenseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout expensePanelLayout = new javax.swing.GroupLayout(expensePanel);
        expensePanel.setLayout(expensePanelLayout);
        expensePanelLayout.setHorizontalGroup(
            expensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expensePanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(expensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddExpense, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(expensePanelLayout.createSequentialGroup()
                        .addGroup(expensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fieldExpenseType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                            .addComponent(fieldValueExpense, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldTimeExpense, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, expensePanelLayout.createSequentialGroup()
                .addContainerGap(645, Short.MAX_VALUE)
                .addComponent(btnBackExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        expensePanelLayout.setVerticalGroup(
            expensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expensePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblAddExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(fieldValueExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(fieldTimeExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(fieldExpenseType, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBackExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        transactionSplit.add(expensePanel, "cardExpense");

        panelDisplay.add(transactionSplit, "cardTransaction");
        transactionSplit.getAccessibleContext().setAccessibleParent(panelDisplay);

        homePanel.setBackground(new java.awt.Color(214, 228, 228));
        homePanel.setToolTipText("");
        homePanel.setRequestFocusEnabled(false);

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 827, Short.MAX_VALUE)
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );

        panelDisplay.add(homePanel, "cardHome");
        homePanel.getAccessibleContext().setAccessibleName("");
        homePanel.getAccessibleContext().setAccessibleParent(panelDisplay);

        historyPanel.setBackground(new java.awt.Color(234, 255, 234));

        javax.swing.GroupLayout historyPanelLayout = new javax.swing.GroupLayout(historyPanel);
        historyPanel.setLayout(historyPanelLayout);
        historyPanelLayout.setHorizontalGroup(
            historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 827, Short.MAX_VALUE)
        );
        historyPanelLayout.setVerticalGroup(
            historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );

        panelDisplay.add(historyPanel, "cardHistory");

        jSplitPane1.setRightComponent(panelDisplay);

        jPanel1.add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelDisplay, "cardHome");
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
       cardLayout.show(panelDisplay, "cardHistory");
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransactionActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelDisplay, "cardTransaction");
    }//GEN-LAST:event_btnTransactionActionPerformed

    private void fieldExpenseTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldExpenseTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldExpenseTypeActionPerformed

    private void fieldValueIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldValueIncomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldValueIncomeActionPerformed

    private void fieldValueIncome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldValueIncome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldValueIncome1ActionPerformed

    private void fieldValueExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldValueExpenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldValueExpenseActionPerformed

    private void fieldTimeIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTimeIncomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTimeIncomeActionPerformed

    private void btnToIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToIncomeActionPerformed
        // TODO add your handling code here:
        cardLayout2.show(transactionSplit, "cardIncome");
    }//GEN-LAST:event_btnToIncomeActionPerformed

    private void btnBackIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackIncomeActionPerformed
        // TODO add your handling code here:
        cardLayout2.show(transactionSplit, "cardTransBase");
    }//GEN-LAST:event_btnBackIncomeActionPerformed

    private void btnBackExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackExpenseActionPerformed
        // TODO add your handling code here:
        cardLayout2.show(transactionSplit, "cardTransBase");
    }//GEN-LAST:event_btnBackExpenseActionPerformed

    private void btnToExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToExpenseActionPerformed
        // TODO add your handling code here:
           cardLayout2.show(transactionSplit, "cardExpense");
    }//GEN-LAST:event_btnToExpenseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackExpense;
    private javax.swing.JButton btnBackIncome;
    public javax.swing.JButton btnHistory;
    public javax.swing.JButton btnHome;
    private javax.swing.JButton btnToExpense;
    private javax.swing.JButton btnToIncome;
    public javax.swing.JButton btnTransaction;
    private javax.swing.JPanel expensePanel;
    private javax.swing.JTextField fieldExpenseType;
    private javax.swing.JTextField fieldTimeExpense;
    private javax.swing.JTextField fieldTimeIncome;
    private javax.swing.JTextField fieldValueExpense;
    private javax.swing.JTextField fieldValueIncome;
    private javax.swing.JTextField fieldValueIncome1;
    private javax.swing.JPanel historyPanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JPanel incomePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblAddExpense;
    private javax.swing.JLabel lblAddIncome;
    public javax.swing.JPanel panelDisplay;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelTransaction;
    private javax.swing.JPanel transactionSplit;
    // End of variables declaration//GEN-END:variables
}
