/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.budgeter.view;

import java.awt.CardLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class jframe extends javax.swing.JFrame {

    /**
     * Creates new form jframe
     */
    CardLayout cardLayout;
    CardLayout cardLayout2;
    int id = 001;
    
    public jframe() {
        initComponents();
        cardLayout = (CardLayout)(panelDisplay.getLayout());
        cardLayout2 = (CardLayout)(transactionSplit.getLayout());
        cardLayout.show(panelDisplay, "cardHome");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        panelMenu = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnTransaction = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        lblBalance = new javax.swing.JLabel();
        panelDisplay = new javax.swing.JPanel();
        transactionSplit = new javax.swing.JPanel();
        panelTransaction = new javax.swing.JPanel();
        btnToIncome = new javax.swing.JButton();
        btnToExpense = new javax.swing.JButton();
        incomePanel = new javax.swing.JPanel();
        lblAddIncome = new javax.swing.JLabel();
        txtTimeIncome = new javax.swing.JTextField();
        txtValueIncome = new javax.swing.JTextField();
        txtDetailIncome = new javax.swing.JTextField();
        btnBackIncome = new javax.swing.JButton();
        btnSubmitIncome = new javax.swing.JButton();
        lblTimeIncome = new javax.swing.JLabel();
        lblValueIncome = new javax.swing.JLabel();
        lblDetailIncome = new javax.swing.JLabel();
        expensePanel = new javax.swing.JPanel();
        lblAddExpense = new javax.swing.JLabel();
        txtTimeExpense = new javax.swing.JTextField();
        txtValueExpense = new javax.swing.JTextField();
        txtDetailExpense = new javax.swing.JTextField();
        btnSubmitExpense = new javax.swing.JButton();
        btnBackExpense = new javax.swing.JButton();
        lblTimeExpense = new javax.swing.JLabel();
        lblValueExpense = new javax.swing.JLabel();
        lblDetailExpense = new javax.swing.JLabel();
        homePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        homeTabel = new javax.swing.JTable();
        lblHomePanel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        historyPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        historyTabel = new javax.swing.JTable();
        lblHistoryPanel = new javax.swing.JLabel();
        btnDeleteRow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setBackground(new java.awt.Color(250, 250, 234));

        btnHome.setBackground(new java.awt.Color(250, 250, 234));
        btnHome.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        btnHome.setText("Home");
        btnHome.setBorder(null);
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.setMaximumSize(new java.awt.Dimension(120, 55));
        btnHome.setMinimumSize(new java.awt.Dimension(120, 55));
        btnHome.setPreferredSize(new java.awt.Dimension(150, 55));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnTransaction.setBackground(new java.awt.Color(250, 250, 234));
        btnTransaction.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        btnTransaction.setText("Transaction");
        btnTransaction.setActionCommand("Expense");
        btnTransaction.setBorder(null);
        btnTransaction.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTransaction.setMaximumSize(new java.awt.Dimension(120, 55));
        btnTransaction.setMinimumSize(new java.awt.Dimension(120, 55));
        btnTransaction.setPreferredSize(new java.awt.Dimension(150, 55));
        btnTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransactionActionPerformed(evt);
            }
        });

        btnHistory.setBackground(new java.awt.Color(250, 250, 234));
        btnHistory.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        btnHistory.setBorder(null);
        btnHistory.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHistory.setLabel("History");
        btnHistory.setMaximumSize(new java.awt.Dimension(120, 55));
        btnHistory.setMinimumSize(new java.awt.Dimension(120, 55));
        btnHistory.setPreferredSize(new java.awt.Dimension(150, 55));
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });

        lblBalance.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 24)); // NOI18N
        lblBalance.setText("Balance :");

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        panelMenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHistory, btnHome, btnTransaction});

        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(lblBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(panelMenu);

        panelDisplay.setBackground(new java.awt.Color(255, 255, 239));
        panelDisplay.setLayout(new java.awt.CardLayout());

        transactionSplit.setLayout(new java.awt.CardLayout());

        panelTransaction.setBackground(new java.awt.Color(243, 243, 231));

        btnToIncome.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        btnToIncome.setText("Income");
        btnToIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToIncomeActionPerformed(evt);
            }
        });

        btnToExpense.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        btnToExpense.setText("Expense");
        btnToExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToExpenseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTransactionLayout = new javax.swing.GroupLayout(panelTransaction);
        panelTransaction.setLayout(panelTransactionLayout);
        panelTransactionLayout.setHorizontalGroup(
            panelTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransactionLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(btnToIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                .addComponent(btnToExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );
        panelTransactionLayout.setVerticalGroup(
            panelTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransactionLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(panelTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnToIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnToExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(427, Short.MAX_VALUE))
        );

        transactionSplit.add(panelTransaction, "cardTransBase");
        panelTransaction.getAccessibleContext().setAccessibleParent(panelDisplay);

        incomePanel.setBackground(new java.awt.Color(243, 243, 231));

        lblAddIncome.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 26)); // NOI18N
        lblAddIncome.setText("Add Income");

        txtTimeIncome.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 20)); // NOI18N
        txtTimeIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeIncomeActionPerformed(evt);
            }
        });

        txtValueIncome.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 20)); // NOI18N
        txtValueIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValueIncomeActionPerformed(evt);
            }
        });

        txtDetailIncome.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 20)); // NOI18N
        txtDetailIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDetailIncomeActionPerformed(evt);
            }
        });

        btnBackIncome.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        btnBackIncome.setText("Back");
        btnBackIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackIncomeActionPerformed(evt);
            }
        });

        btnSubmitIncome.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        btnSubmitIncome.setText("Submit");
        btnSubmitIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitIncomeActionPerformed(evt);
            }
        });

        lblTimeIncome.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 20)); // NOI18N
        lblTimeIncome.setText("Time Income");

        lblValueIncome.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 20)); // NOI18N
        lblValueIncome.setText("Value Income");

        lblDetailIncome.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 20)); // NOI18N
        lblDetailIncome.setText("Detail Income");

        javax.swing.GroupLayout incomePanelLayout = new javax.swing.GroupLayout(incomePanel);
        incomePanel.setLayout(incomePanelLayout);
        incomePanelLayout.setHorizontalGroup(
            incomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incomePanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(incomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(incomePanelLayout.createSequentialGroup()
                        .addComponent(btnSubmitIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 539, Short.MAX_VALUE)
                        .addComponent(btnBackIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(incomePanelLayout.createSequentialGroup()
                        .addGroup(incomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(incomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtValueIncome)
                                .addComponent(txtTimeIncome)
                                .addComponent(txtDetailIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDetailIncome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(incomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblValueIncome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                .addComponent(lblTimeIncome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))
                            .addComponent(lblAddIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        incomePanelLayout.setVerticalGroup(
            incomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incomePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblAddIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblTimeIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimeIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValueIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValueIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDetailIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDetailIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addGroup(incomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmitIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );

        txtTimeIncome.getAccessibleContext().setAccessibleName("");
        txtValueIncome.getAccessibleContext().setAccessibleName("");
        txtDetailIncome.getAccessibleContext().setAccessibleName("");

        transactionSplit.add(incomePanel, "cardIncome");

        expensePanel.setBackground(new java.awt.Color(243, 243, 231));

        lblAddExpense.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 26)); // NOI18N
        lblAddExpense.setText("Add Expense");

        txtTimeExpense.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 20)); // NOI18N
        txtTimeExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeExpenseActionPerformed(evt);
            }
        });

        txtValueExpense.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 20)); // NOI18N
        txtValueExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValueExpenseActionPerformed(evt);
            }
        });

        txtDetailExpense.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 20)); // NOI18N
        txtDetailExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDetailExpenseActionPerformed(evt);
            }
        });

        btnSubmitExpense.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        btnSubmitExpense.setText("Submit");
        btnSubmitExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitExpenseActionPerformed(evt);
            }
        });

        btnBackExpense.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        btnBackExpense.setText("Back");
        btnBackExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackExpenseActionPerformed(evt);
            }
        });

        lblTimeExpense.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 20)); // NOI18N
        lblTimeExpense.setText("Time Expense");

        lblValueExpense.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 20)); // NOI18N
        lblValueExpense.setText("Value Expense");

        lblDetailExpense.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 20)); // NOI18N
        lblDetailExpense.setText("Detail Expense");

        javax.swing.GroupLayout expensePanelLayout = new javax.swing.GroupLayout(expensePanel);
        expensePanel.setLayout(expensePanelLayout);
        expensePanelLayout.setHorizontalGroup(
            expensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expensePanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(expensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(expensePanelLayout.createSequentialGroup()
                        .addComponent(btnSubmitExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBackExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(expensePanelLayout.createSequentialGroup()
                        .addGroup(expensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblAddExpense, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTimeExpense, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblValueExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDetailExpense, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDetailExpense, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                            .addComponent(txtValueExpense, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTimeExpense, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(503, Short.MAX_VALUE))))
        );
        expensePanelLayout.setVerticalGroup(
            expensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expensePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblAddExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblTimeExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValueExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValueExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimeExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDetailExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDetailExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addGroup(expensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmitExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );

        transactionSplit.add(expensePanel, "cardExpense");

        panelDisplay.add(transactionSplit, "cardTransaction");
        transactionSplit.getAccessibleContext().setAccessibleParent(panelDisplay);

        homePanel.setBackground(new java.awt.Color(243, 243, 231));
        homePanel.setToolTipText("");
        homePanel.setRequestFocusEnabled(false);

        homeTabel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        homeTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Transaction Type", "Amount", "Detail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(homeTabel);

        lblHomePanel.setBackground(new java.awt.Color(153, 255, 153));
        lblHomePanel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        lblHomePanel.setText("History Bulan Sekarang");

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel1.setText("Total Expense : ");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel2.setText("Total Income : ");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(lblHomePanel))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homePanelLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(199, 199, 199)
                                .addComponent(jLabel1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblHomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        panelDisplay.add(homePanel, "cardHome");
        homePanel.getAccessibleContext().setAccessibleName("");
        homePanel.getAccessibleContext().setAccessibleParent(panelDisplay);

        historyPanel.setBackground(new java.awt.Color(243, 243, 231));

        historyTabel.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        historyTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "TransactionType", "Amount", "Detail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(historyTabel);
        if (historyTabel.getColumnModel().getColumnCount() > 0) {
            historyTabel.getColumnModel().getColumn(0).setResizable(false);
            historyTabel.getColumnModel().getColumn(1).setResizable(false);
            historyTabel.getColumnModel().getColumn(2).setResizable(false);
            historyTabel.getColumnModel().getColumn(3).setResizable(false);
            historyTabel.getColumnModel().getColumn(4).setResizable(false);
        }

        lblHistoryPanel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 30)); // NOI18N
        lblHistoryPanel.setText("All History");

        btnDeleteRow.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 28)); // NOI18N
        btnDeleteRow.setText(" Delete Row");
        btnDeleteRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout historyPanelLayout = new javax.swing.GroupLayout(historyPanel);
        historyPanel.setLayout(historyPanelLayout);
        historyPanelLayout.setHorizontalGroup(
            historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyPanelLayout.createSequentialGroup()
                .addGroup(historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(historyPanelLayout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(lblHistoryPanel))
                    .addGroup(historyPanelLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteRow))))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        historyPanelLayout.setVerticalGroup(
            historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, historyPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblHistoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnDeleteRow, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        panelDisplay.add(historyPanel, "cardHistory");

        jSplitPane1.setRightComponent(panelDisplay);

        jPanel1.add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelDisplay, "cardHome");
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
       cardLayout.show(panelDisplay, "cardHistory");
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransactionActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelDisplay, "cardTransaction");
    }//GEN-LAST:event_btnTransactionActionPerformed

    private void txtDetailExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDetailExpenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDetailExpenseActionPerformed

    private void txtValueIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValueIncomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValueIncomeActionPerformed

    private void txtDetailIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDetailIncomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDetailIncomeActionPerformed

    private void txtValueExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValueExpenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValueExpenseActionPerformed

    private void txtTimeIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeIncomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeIncomeActionPerformed

    private void btnToIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToIncomeActionPerformed
        // TODO add your handling code here:
        cardLayout2.show(transactionSplit, "cardIncome");
    }//GEN-LAST:event_btnToIncomeActionPerformed

    private void btnBackIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackIncomeActionPerformed
        // TODO add your handling code here:
        cardLayout2.show(transactionSplit, "cardTransBase");
    }//GEN-LAST:event_btnBackIncomeActionPerformed

    private void btnSubmitExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitExpenseActionPerformed
        // TODO add your handling code here:
        if (txtTimeExpense.getText().equals("")|| txtValueExpense.getText().equals("")||txtDetailExpense.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Pastikan masukkan seluruh data");
        }else{
            String data[] = {Integer.toString(id),
                txtTimeExpense.getText(),
                "Expense", 
                txtValueExpense.getText(),
                txtDetailExpense.getText()};
            DefaultTableModel historyAll = (DefaultTableModel) historyTabel.getModel();
            historyAll.addRow(data);
            JOptionPane.showMessageDialog(this, "Data added ! ");
            txtDetailExpense.setText(""); txtTimeExpense.setText(""); txtValueExpense.setText("");
            id++;
        }
    }//GEN-LAST:event_btnSubmitExpenseActionPerformed

    private void btnToExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToExpenseActionPerformed
        // TODO add your handling code here:
           cardLayout2.show(transactionSplit, "cardExpense");
    }//GEN-LAST:event_btnToExpenseActionPerformed

    private void btnBackExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackExpenseActionPerformed
        // TODO add your handling code here:
        cardLayout2.show(transactionSplit, "cardTransBase");
    }//GEN-LAST:event_btnBackExpenseActionPerformed

    private void btnSubmitIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitIncomeActionPerformed
        // TODO add your handling code here:
        if (txtTimeIncome.getText().equals("")|| txtValueIncome.getText().equals("")||txtDetailIncome.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Pastikan masukkan seluruh data");
        }else{
            String data[] = {Integer.toString(id),
                txtTimeIncome.getText(),
                "Income",
                txtValueIncome.getText(),
                txtDetailIncome.getText()};
            
            DefaultTableModel historyAll = (DefaultTableModel) historyTabel.getModel();
            historyAll.addRow(data);
            JOptionPane.showMessageDialog(this, "Data added ! ");
            txtDetailIncome.setText(""); txtTimeIncome.setText(""); txtValueIncome.setText("");
            id++;
        }
    }//GEN-LAST:event_btnSubmitIncomeActionPerformed

    private void btnDeleteRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRowActionPerformed
        // TODO add your handling code here:
        DefaultTableModel historyAll = (DefaultTableModel) historyTabel.getModel();
        
        if (historyTabel.getSelectedRowCount()==1){
            historyAll.removeRow(historyTabel.getSelectedRow());
        }else{
            if (historyTabel.getRowCount() == 0){
                JOptionPane.showMessageDialog(this, "Table is Empty");
            }else{
                JOptionPane.showMessageDialog(this, "Please select row");
            }
        }
    }//GEN-LAST:event_btnDeleteRowActionPerformed

    private void txtTimeExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeExpenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeExpenseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackExpense;
    private javax.swing.JButton btnBackIncome;
    private javax.swing.JButton btnDeleteRow;
    public javax.swing.JButton btnHistory;
    public javax.swing.JButton btnHome;
    private javax.swing.JButton btnSubmitExpense;
    private javax.swing.JButton btnSubmitIncome;
    private javax.swing.JButton btnToExpense;
    private javax.swing.JButton btnToIncome;
    public javax.swing.JButton btnTransaction;
    private javax.swing.JPanel expensePanel;
    private javax.swing.JPanel historyPanel;
    private javax.swing.JTable historyTabel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JTable homeTabel;
    private javax.swing.JPanel incomePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblAddExpense;
    private javax.swing.JLabel lblAddIncome;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblDetailExpense;
    private javax.swing.JLabel lblDetailIncome;
    private javax.swing.JLabel lblHistoryPanel;
    private javax.swing.JLabel lblHomePanel;
    private javax.swing.JLabel lblTimeExpense;
    private javax.swing.JLabel lblTimeIncome;
    private javax.swing.JLabel lblValueExpense;
    private javax.swing.JLabel lblValueIncome;
    public javax.swing.JPanel panelDisplay;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelTransaction;
    private javax.swing.JPanel transactionSplit;
    private javax.swing.JTextField txtDetailExpense;
    private javax.swing.JTextField txtDetailIncome;
    private javax.swing.JTextField txtTimeExpense;
    private javax.swing.JTextField txtTimeIncome;
    private javax.swing.JTextField txtValueExpense;
    private javax.swing.JTextField txtValueIncome;
    // End of variables declaration//GEN-END:variables
}
